# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\blur.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_blur(object):
    def setupUi(self, blur):
        blur.setObjectName("blur")
        blur.resize(340, 240)
        self.label_4 = QtWidgets.QLabel(blur)
        self.label_4.setGeometry(QtCore.QRect(110, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(blur)
        self.label.setGeometry(QtCore.QRect(50, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(blur)
        self.comboBox.setGeometry(QtCore.QRect(120, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(blur)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 341, 241))
        self.label_7.setStyleSheet("border:8px solid rgb(0, 170, 0);\n"
"background-color: rgb(198, 198, 198);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(blur)
        self.pushButton.setGeometry(QtCore.QRect(110, 170, 111, 51))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px\n"
"}\n"
"#pushButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(blur)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(blur)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_7.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.comboBox_2.raise_()

        self.retranslateUi(blur)
        QtCore.QMetaObject.connectSlotsByName(blur)

    def retranslateUi(self, blur):
        _translate = QtCore.QCoreApplication.translate
        blur.setWindowTitle(_translate("blur", "Form"))
        self.label_4.setText(_translate("blur", "平滑处理"))
        self.label.setText(_translate("blur", "核大小"))
        self.comboBox.setItemText(0, _translate("blur", "(1,1)"))
        self.comboBox.setItemText(1, _translate("blur", "(3,3)"))
        self.comboBox.setItemText(2, _translate("blur", "(5,5)"))
        self.comboBox.setItemText(3, _translate("blur", "(7,7)"))
        self.comboBox.setItemText(4, _translate("blur", "(9,9)"))
        self.comboBox.setItemText(5, _translate("blur", "(11,11)"))
        self.comboBox.setItemText(6, _translate("blur", "(13,13)"))
        self.comboBox.setItemText(7, _translate("blur", "(15,15)"))
        self.comboBox.setItemText(8, _translate("blur", "(17,17)"))
        self.comboBox.setItemText(9, _translate("blur", "(19,19)"))
        self.pushButton.setText(_translate("blur", "确定"))
        self.label_2.setText(_translate("blur", "类型"))
        self.comboBox_2.setItemText(0, _translate("blur", "高斯模糊"))
        self.comboBox_2.setItemText(1, _translate("blur", "均值模糊"))
        self.comboBox_2.setItemText(2, _translate("blur", "方框模糊"))
