# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\ui\child.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(167, 162)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(7, 7, 70, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);    \n"
"    border-bottom-right-radius:12px;\n"
"}\n"
"#pushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(7, 90, 70, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-top-right-radius:12px;\n"
"}\n"
"#pushButton_2:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 7, 70, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-bottom-left-radius:12px;\n"
"}\n"
"#pushButton_3:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 90, 70, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-top-left-radius:12px;\n"
"}\n"
"#pushButton_4:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 167, 162))
        self.label.setStyleSheet("border:7px solid rgb(0, 170, 0);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "腐蚀"))
        self.pushButton_2.setText(_translate("Form", "膨胀"))
        self.pushButton_3.setText(_translate("Form", "礼帽"))
        self.pushButton_4.setText(_translate("Form", "黑帽"))
