# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\ui\contours.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contours(object):
    def setupUi(self, contours):
        contours.setObjectName("contours")
        contours.resize(343, 240)
        self.label_4 = QtWidgets.QLabel(contours)
        self.label_4.setGeometry(QtCore.QRect(110, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_2 = QtWidgets.QSpinBox(contours)
        self.spinBox_2.setGeometry(QtCore.QRect(160, 120, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(20)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_7 = QtWidgets.QLabel(contours)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 341, 241))
        self.label_7.setStyleSheet("border:8px solid rgb(0, 170, 0);\n"
"background-color: rgb(198, 198, 198);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(contours)
        self.label_6.setGeometry(QtCore.QRect(70, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(contours)
        self.label_3.setGeometry(QtCore.QRect(70, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(contours)
        self.comboBox.setGeometry(QtCore.QRect(160, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(contours)
        self.pushButton.setGeometry(QtCore.QRect(120, 170, 111, 51))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px\n"
"}\n"
"#pushButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_7.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.spinBox_2.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()

        self.retranslateUi(contours)
        QtCore.QMetaObject.connectSlotsByName(contours)

    def retranslateUi(self, contours):
        _translate = QtCore.QCoreApplication.translate
        contours.setWindowTitle(_translate("contours", "Form"))
        self.label_4.setText(_translate("contours", "图像轮廓"))
        self.label_6.setText(_translate("contours", "轮廓粗细"))
        self.label_3.setText(_translate("contours", "轮廓颜色"))
        self.comboBox.setItemText(0, _translate("contours", "红色"))
        self.comboBox.setItemText(1, _translate("contours", "蓝色"))
        self.comboBox.setItemText(2, _translate("contours", "绿色"))
        self.comboBox.setItemText(3, _translate("contours", "黄色"))
        self.comboBox.setItemText(4, _translate("contours", "紫色"))
        self.comboBox.setItemText(5, _translate("contours", "青色"))
        self.comboBox.setItemText(6, _translate("contours", "黑色"))
        self.comboBox.setItemText(7, _translate("contours", "白色"))
        self.pushButton.setText(_translate("contours", "确定"))
