# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\gradient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gradient(object):
    def setupUi(self, gradient):
        gradient.setObjectName("gradient")
        gradient.resize(341, 241)
        self.label_4 = QtWidgets.QLabel(gradient)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(gradient)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 341, 241))
        self.label_7.setStyleSheet("border:8px solid rgb(0, 170, 0);\n"
"background-color: rgb(198, 198, 198);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(gradient)
        self.label.setGeometry(QtCore.QRect(70, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(gradient)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(gradient)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(gradient)
        self.pushButton.setGeometry(QtCore.QRect(120, 170, 111, 51))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px\n"
"}\n"
"#pushButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(gradient)
        self.spinBox.setGeometry(QtCore.QRect(140, 130, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setSingleStep(2)
        self.spinBox.setObjectName("spinBox")
        self.label_7.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.comboBox_2.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.spinBox.raise_()

        self.retranslateUi(gradient)
        QtCore.QMetaObject.connectSlotsByName(gradient)

    def retranslateUi(self, gradient):
        _translate = QtCore.QCoreApplication.translate
        gradient.setWindowTitle(_translate("gradient", "Form"))
        self.label_4.setText(_translate("gradient", "图像梯度"))
        self.label.setText(_translate("gradient", "类型"))
        self.comboBox_2.setItemText(0, _translate("gradient", "Sobel"))
        self.comboBox_2.setItemText(1, _translate("gradient", "Scharr"))
        self.comboBox_2.setItemText(2, _translate("gradient", "Laplacian"))
        self.label_2.setText(_translate("gradient", "核大小"))
        self.pushButton.setText(_translate("gradient", "确定"))
