# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\logon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogonWindow(object):
    def setupUi(self, LogonWindow):
        LogonWindow.setObjectName("LogonWindow")
        LogonWindow.resize(1057, 691)
        
        #隐藏边框
        LogonWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        LogonWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.centralwidget = QtWidgets.QWidget(LogonWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 90, 360, 500))
        self.label.setStyleSheet("border-image: url(:/images/images/robot.png);\n"
"border-top-left-radius:40px;\n"
"border-bottom-left-radius:40px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 90, 450, 500))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:40px;\n"
"border-bottom-right-radius:40px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(595, 480, 160, 60))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"#pushButton:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 110, 31, 21))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"#pushButton_2:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 170, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 87 30pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        LogonWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogonWindow)
        self.pushButton_2.clicked.connect(LogonWindow.close)
        self.pushButton.clicked.connect(LogonWindow.close)
        QtCore.QMetaObject.connectSlotsByName(LogonWindow)

    def retranslateUi(self, LogonWindow):
        _translate = QtCore.QCoreApplication.translate
        LogonWindow.setWindowTitle(_translate("LogonWindow", "MainWindow"))
        self.pushButton.setText(_translate("LogonWindow", "开始"))
        self.label_3.setText(_translate("LogonWindow", "APEX顶猎专属PS"))
import resource_rc
