# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86188\AppData\Local\vscode\workspace\VS-Code\ps\ps.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 40, 70, 65))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/tan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(155, 40, 70, 65))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_2:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 40, 70, 65))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_3:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(305, 40, 70, 65))
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_4:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 40, 70, 65))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_5:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 139, 755, 422))
        self.label.setStyleSheet("border:5px solid rgb(0, 170, 0);\n"
"image: url(:/images/images/background.png);\n"
"\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(455, 40, 70, 65))
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_6:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 40, 70, 65))
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_7:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(5, 40, 70, 65))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_8:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 5, 80, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"background-color: rgb(255, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(605, 40, 70, 65))
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_9:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 5, 30, 30))
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:2px solid rgb(97, 97, 97);\n"
"    border-radius:10px\n"
"}\n"
"#pushButton_10:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 5, 30, 30))
        self.pushButton_11.setStyleSheet("#pushButton_11{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:2px solid  rgb(97, 97, 97);\n"
"    border-radius:10px\n"
"}\n"
"#pushButton_11:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_11.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 755, 141))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("border:5px solid rgb(0, 170, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(680, 40, 70, 65))
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
"    background-color: rgb(97, 97, 97);\n"
"    border:1px solid rgb(97, 97, 97);\n"
"    border-radius:12px\n"
"}\n"
"#pushButton_12:hover{\n"
"    background-color: rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 110, 51, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 110, 51, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(305, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(385, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 110, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(550, 110, 31, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(610, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(690, 110, 54, 12))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_3.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionwenjian = QtWidgets.QAction(MainWindow)
        self.actionwenjian.setIconVisibleInMenu(True)
        self.actionwenjian.setObjectName("actionwenjian")
        self.actionwenjian.setShortcut('ctrl+o')
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action.setShortcut('ctrl+s')
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_2.setShortcut('ctrl+z')
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_3.setShortcut('ctrl+y')
        self.menu.addAction(self.actionwenjian)
        self.menu.addAction(self.action)
        self.menu_E.addAction(self.action_2)
        self.menu_E.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APEX顶猎专属PS"))
        self.label_2.setText(_translate("MainWindow", "图像操作"))
        self.label_4.setText(_translate("MainWindow", "显示原图"))
        self.label_5.setText(_translate("MainWindow", "灰度图"))
        self.label_6.setText(_translate("MainWindow", "平滑处理"))
        self.label_7.setText(_translate("MainWindow", "关键点"))
        self.label_8.setText(_translate("MainWindow", "图像梯度"))
        self.label_9.setText(_translate("MainWindow", "图像轮廓"))
        self.label_10.setText(_translate("MainWindow", "形态学"))
        self.label_11.setText(_translate("MainWindow", "抠图"))
        self.label_12.setText(_translate("MainWindow", "添加水印"))
        self.label_13.setText(_translate("MainWindow", "直方图"))
        self.menu.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(E)"))
        self.actionopen.setText(_translate("MainWindow", "OPEN"))
        self.actionwenjian.setText(_translate("MainWindow", "打开..."))
        self.action.setText(_translate("MainWindow", "另存为..."))
        self.action_2.setText(_translate("MainWindow", "撤销"))
        self.action_3.setText(_translate("MainWindow", "还原"))
import resource_rc
